# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Mxn
tagline:          ‘1111’
description:      ‘22222’
url:              https://github.com/mxn21

author:
  name:           ‘soul.mxn’
  url:            https://github.com/mxn21

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name :mxn
