# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            'soul.Mxn'
tagline:          '竹杖芒鞋轻胜马,一蓑烟雨任平生'
description:      '我的github'
url:              https://github.com/mxn21

author:
  name:           'mxn'
  url:            https://github.com/mxn21

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name :mxn
