# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            'Mxn's blog'
name:            'mxn21的博客'
tagline:          '一日三省吾身，续之或者改之'
description:      '守拙以清心,淡然而浅笑'
url:              https://github.com/mxn21
blogurl:          http://souly.cn

author:
  name:           'mxn'
  url:            https://github.com/mxn21

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name :souly
